SudokuSolver/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^solve/', include('solve.urls', namespace="solve")),
	url(r'^admin/', include(admin.site.urls)),
)

solve/urls.py
from django.conf.urls import patterns, url
from solve import views

urlpatterns = patterns('',
	url(r'^input/$', views.input_sudoku, name='input'),
	url(r'^display/$', views.display_sudoku, name='display'),
	url(r'^solution/$', views.solve_sudoku, name='solution'),
	url(r'^nosolution/$', views.no_solution, name='no_solution'),
)

solve/views.py
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseServerError, Http404
from django.shortcuts import get_object_or_404, render, render_to_response
from django.core.urlresolvers import reverse
from django.views import generic
from solution import Solution
from django.core.context_processors import csrf

def input_sudoku(request):
	c = {}
	c.update(csrf(request))
	return render_to_response('solve/input.html', c)

def no_solution(request):
	return render(request, 'solve/unsolvable.html')

def solve_sudoku(request):
	sudoku_input = []
	for i in range(0, 81):
		input_character = request.POST[str(i)]
		if len(input_character) == 0:
			sudoku_input.append('.')
		else:
			sudoku_input.append(input_character)

	sudoku_solution = Solution(sudoku_input).return_grid()
	# Save session to display the contents of the solution of the sudoku
	# in the display_sudoku view
	# Always redirect after POST.
	request.session['sudoku_solution'] = repr(sudoku_solution)

	if not sudoku_solution:
		return HttpResponseRedirect(reverse('solve:no_solution'))
	else:
		return HttpResponseRedirect(reverse('solve:display'))

def display_sudoku(request):
	sudoku_solution = request.session.get('sudoku_solution', None)

	if sudoku_solution is not None:
		sudoku_solution = eval(sudoku_solution)
	else:
		return HttpResponseRedirect(reverse('solve:no_solution'))

	return render(request, 'solve/display.html', {"grid":sudoku_solution})

solve/templates/solve/display.html
{% extends "base.html" %}
{% load extras %}

{% block content %}

<div class="container" id="sudoku">
	<h2 class="padding">Solution</h2>
	<table class="table table-bordered">
	<tbody>
		{% for row in grid %}
			<tr>
			{% for element in row %}
				<td>{{ element }}</td>
			{% endfor %}
			</tr>
		{% endfor %}
	</tbody>
	</table>
	<form action="{% url 'solve:input' %}">
		<input type="submit" class="btn btn-primary" value="Solve Another One"/>
	</form>

</div>
{% for posted_value in nothing %}
	{{ posted_value }}
{% endfor %}

{% endblock %}

solve/templates/solve/input.html
{% extends "base.html" %}
{% load extras %}
{% load static %}

{% block stylesheets %}
	<link rel="stylesheet" href="{% static 'solve/main.css' %}">
{% endblock %}

{% block content %}

<div class="container" id="sudoku">
	<h2 class="padding">Enter Grid</h2>
	<form name="sudokuInput" method="post" action="{% url 'solve:solution' %}" id="gridForm">
	{% csrf_token %}
		<table class="table table-bordered" id="sudokuInputGrid">
		<tbody>
			{% for row in "9"|range_list %}
				<tr class="row">
				{% with forloop.counter0 as out_counter %}
				{% for element in "9"|range_list %}
					{% with out_counter|multiply:9 as in_counter %}
					{% with in_counter|addition:forloop.counter0 as unique_id %}
					<td id="cell-element{{ unique_id }}" class="valid-value">
						<!-- ID of each square is set to to an integer - (0 to 80) inclusive, ROW MAJOR -->
							<input name="{{ unique_id }}" id="{{ unique_id }}" type="number" min="1" max="9" style="border:none;" class="input-sm"/>
					</td>
					{% endwith %}
					{% endwith %}
				{% endfor %}
				{% endwith %}
				</tr>
			{% endfor %}
		</tbody>
		</table>
	<input type="submit" name="submit" id="submit" class="btn btn-primary"/>
</form>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
	$(document).ready(function() {
		var cells = new Array();
		for (var i = 0; i < 81; i++) {
			cells.push(i);
		}
		var valid_cells = new Array();
		for (var i = 0; i < 81; i++) {
			valid_cells.push(true);
		}
		$('#gridForm').submit(function() {
			var is_grid_valid = true;
			$(valid_cells).each(function(index) {
				is_grid_valid = is_grid_valid & valid_cells[index];
			});
			if (is_grid_valid == 0) {
				alert('Enter Valid Data Into The Grid Before Submit');
				return false;
			}
			else {
				return true;
			}
		});
		verification(cells, valid_cells);

    });
	function verification (cells, valid_cells) {
		$(cells).each(function(index) {
			var input_box_id = '#' + index.toString();
			var cell_id = '#cell-element' + index.toString();
			$(input_box_id).change(function() {
				valid_cells[index] = displayAlert($(this).val(), cell_id);
			});
		});
	}
	function displayAlert(input_value, cell_id, is_cell_valid) {
		if (input_value == "") {
			$(cell_id).removeClass('invalid-value').addClass('valid-value');
			console.log('Empty Cell');
			return true;
		}
		console.log('Not an Empty cell');
		if (!$.isNumeric(input_value)) {
			$(cell_id).removeClass('valid-value').addClass('invalid-value');
			console.log('not a numeric value');
			alert('Enter Numeric Value');
			return false;
		}
		else {
			console.log('numeric value');
			if (input_value < 1 || input_value > 9) {
				$(cell_id).removeClass('valid-value').addClass('invalid-value');
				console.log('invalid range');
				alert('Enter A Number Between 1 and 9 inclusive');
				return false;
			}
			else {
				console.log('valid input');
				$(cell_id).removeClass('invalid-value').addClass('valid-value');
				return true;
			}
		}
	}
</script>
{% endblock %}

solve/templates/solve/unsolvable.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
	<link rel="stylesheet" href="{% static 'solve/main.css' %}">
{% endblock %}

{% block content %}
<div class="container">
	<h2 class="padding" style='text-align: center;'>NO SOLUTION</h2>
	<br><br>
	<form action="{% url 'solve:input' %}" class="text-center">
		<input type="submit" class="btn btn-primary" value="Enter Valid Grid"/>
	</form>
</div>

{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="{% static 'jquery.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	{% block stylesheets %}{% endblock %}
</head>

<body>
	<div class="container">
	</div>
 	<div class="navbar navbar-inverse">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'home' %}">Sudoku Solver</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					{% block nav_bar %} {% endblock %}
				</ul>
			</div>
		</div>
	</div>
	{% block content %}{% endblock %}

<div id="wrap">
	<div id="main" class="container clear-top"></div>
</div>

<footer>
	<div class="container">
		By <a href="https://github.com/sourcecode123">Aditya Muttur</a>, 2013
	</div>
</footer>

</body>
</html>
{% block scripts %}
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}

<div class="container" id="sudoku">
	<h1 class="padding">Django Sudoku Solver</h2>
	<form action="{% url 'solve:input' %}">
		<input type="submit" class="btn btn-info btn-lg" href="{% url 'solve:input' %}" value="Get Solving"/>
	</form>
</form>
</div>

{% endblock %}